cars_df = read.csv("~/Downloads/cars.csv")
dim(cars_df)
summary(cars_df)
mean(cars_df$Horsepower)
sum(cars_df$AWD)
sum(cars_df$Minivan) / nrow(cars_df)
cars_df$AWDPickup <- ifelse(cars_df$AWD == 1 & cars_df$Pickup == 1, 1, 0)
sum(cars_df$AWDPickup)
ifelse(cars_df$RWD == 1 & cars_df$Pickup == 1, 1, 0)
sum(cars_df$Pickup)
summary(cars_df)
sum(cars_df$AWD)
sum(cars_df$RWD)
